[package]
name = "object_oriented_design_pattern"
version = "0.1.0"
authors = ["dishankjj <D@ntE786>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
